// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251104233502_FixCascadeDelete")]
    partial class FixCascadeDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ListId")
                        .HasColumnType("int");

                    b.Property<string>("Resenia")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "Jane Austen",
                            Genero = "Romance",
                            ListId = 2,
                            Titulo = "Orgullo y Prejuicio"
                        },
                        new
                        {
                            Id = 2,
                            Autor = "J.R.R. Tolkien",
                            Genero = "Fantasía",
                            ListId = 1,
                            Titulo = "El Hobbit"
                        },
                        new
                        {
                            Id = 3,
                            Autor = "Gabriel García Márquez",
                            Genero = "Realismo mágico",
                            ListId = 1,
                            Titulo = "Cien años de soledad"
                        });
                });

            modelBuilder.Entity("Domain.Entities.ReadingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreadorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<bool>("EsCompartida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CreadorId");

                    b.ToTable("ReadingLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreadorId = 1,
                            Descripcion = "Libros favoritos",
                            EsCompartida = false,
                            Titulo = "Favoritos de Valen"
                        },
                        new
                        {
                            Id = 2,
                            CreadorId = 2,
                            Descripcion = "Libros de programación",
                            EsCompartida = false,
                            Titulo = "Lecturas de Anto"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "valen@gmail.com",
                            Nombre = "Valentina García",
                            Password = "$2a$11$ZnzvKLqafNLyvTr5U0dFiusJZErC4oT9U8r6fzgg0jRSD4soRFqqG",
                            Rol = "usuario"
                        },
                        new
                        {
                            Id = 2,
                            Email = "anto@gmail.com",
                            Nombre = "Antonella Garcia",
                            Password = "$2a$11$LzKuH4GVMrFD/bvl6YREzeMT4lB3QEza7no1pVmV59aeMRpTfXBYm",
                            Rol = "usuario"
                        },
                        new
                        {
                            Id = 3,
                            Email = "giuli@gmail.com",
                            Nombre = "Giuliana Alonzo",
                            Password = "$2a$11$LmIDsjg5EtLFN3z9zY7Td.Vuk5ReV3tBxF9erj.vS2BW3O75hqszC",
                            Rol = "admin"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LibroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Votes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LibroId = 1,
                            UsuarioId = 1,
                            Valor = 5
                        },
                        new
                        {
                            Id = 2,
                            LibroId = 2,
                            UsuarioId = 2,
                            Valor = 4
                        },
                        new
                        {
                            Id = 3,
                            LibroId = 3,
                            UsuarioId = 2,
                            Valor = 5
                        });
                });

            modelBuilder.Entity("Domain.Entities.Book", b =>
                {
                    b.HasOne("Domain.Entities.ReadingList", "ListaLectura")
                        .WithMany("Libros")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaLectura");
                });

            modelBuilder.Entity("Domain.Entities.ReadingList", b =>
                {
                    b.HasOne("Domain.Entities.User", "Creador")
                        .WithMany("ListasCreadas")
                        .HasForeignKey("CreadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("Domain.Entities.Vote", b =>
                {
                    b.HasOne("Domain.Entities.Book", "Libro")
                        .WithMany("Votos")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Usuario")
                        .WithMany("Votos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Libro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Book", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("Domain.Entities.ReadingList", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("ListasCreadas");

                    b.Navigation("Votos");
                });
#pragma warning restore 612, 618
        }
    }
}
